version: '3'
services:
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "pass@123"
          MSSQL_PID: Express
        ports:
          - "1433:1433"
